language: scala
scala:
- 2.12.3
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.3
    env: COMMAND=ci-all PUBLISH=true
script:
- sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COMMAND
- sbt coverageReport
after_success:
- sbt coveralls
- ./project/publish
env:
  global:
  - secure: Y5VJ4oO2sJ5BbZBesNT6QAP0yvJTbZizpkczb/o0AuUqzr98WN5OkADQQqsPds0k6hEFT0xzQRcVwtI8Jt3iR167urkn3mhmXMbUMFxjnaL4WoA8BYAy6oHRBr5nCwoenF1R4cB1tH9a/xnjzD5WRC648P6TfLshZxhSTcbnrR7gORU/6HTV8s3ecYEmkFQqSfCCKpUGYK/tgdLeJqHNznxsNhA+Wkox6lqoD1eZ9mjgSRzkl3ARYU8FHXtJHTx2LXiafvf0jPO/L43vFkw7xG0mlqMXdolbRA213ASYczxHlt2nqin4+Edk4Bqnz8ltflymhn9uFSVXhR1a29ALRXEzDaXF49SmZYJJ2KE5clCZxykFUV+3w/0vZ22JGHx1OKodBJpk5+WlbzFphNNTMWxA1yIslh0FEwG2OR4taq11ttSFnVJhobqOQDwnHxk3PX0hVdqbI8sZyfDmNg7633QkQa8cGTJCT2tkAoK/jmGx99CcAkAjshzVGN2XTrcjufGY8rNpnrSX0Qm0iVPxOfjeIBZiwPjr7sggMpoRdeCUEzglgOwiRp0MItdOj+tIdAbOytX9iPD8FaV4qoeDne8H6e2Eo+Iwk0ADGf8gaKjADaTzxXMJs7fEx4wXchfO+xRO860aKINzJ03OTD75caOKgrcsm0TiJg+2Rr5636s=
  - secure: sTREI7pMWqfqeJLhn3fUz2mPOP6xtkgRwDCnmTUydAbU4yeggDU/0Jxvio4j6hq/BZ9KhMwJtlPCYx6CmJWaG4/KnNnv5yIKr2DlhyU1bCMiqQf7AHwj10zHqpZixvjHvekKJcV/MCkHPX2VJSL7jYQqQRy+SZ2sc2O6L5g3zmZrW0zPQVO9LQif5mEZxeDzQl1DZhLiTvukj72PPvt2eA7LDwIws9XYb58/XpQnN9F/KmqvIy9/M5WaPtYLPkqwUZrbuY9elvaSNvsLp20X+bOOdFHXgsWn8AJ3827mJxAymqwVXAFSktbpnEW62MRKolAlFW6Qxlr3/zCyfkRhtHXXTBzOeuLFvunWJo8hn0WwZU2Zl8MqsAc8mJ+C4n4dLXIrpRamd7jJ7kECMoH8FuUz8SvX7R+7l/VQvJEilcCWTFS0thNsbM8ACb/nULrLZ9NkPcnKX7vGy3nCDkLu0I2yT+wdPCHfdCZ4e4USafd2pDmEyfSC+AcnTnyj4zjZv8ZuLTElN+oXr83RclT0KOyDbnTcahl6/5W7wNKwEv4Seb/1n9BdsOUVD5B6IlhPWZjHzNJIFAW2lkSezvpz1xmOCNOmLG+TB2PB74QkA7usoSKTCh8PILzFr/EZQ8qe92XstKXZYG0EanZnXPI+ygKxS6qudEDG2PRWsHF+030=
  - secure: LbUhjxfPugAL6UGiW56KAiF/vZCtIGW3gI1wQ+VkNmrBYAYpppm5y54rc9EMus+mZbBBqwL4RwMN0J1B/4UM6AcbLtWmbtTks9WXdDXwyBsUgIU7mpCM5xZqfh42TtZV+ypGf569RqATLnRlcYItZoxXjVisk7xuSXv4JFpraTgi2xJPY7wcOvPBq+Tk2835JovSRrZekA53R+hw/XX1Lr/kPj9aCSLny/dOwXy5/Sq5TbZF3hRNTLjdGO0q4I9Q+d5xlHVxLz/iNyJZRyUYiG3O9Zq+yGGpWyFvbWZs9xPCpsSsEQJl8yHNwINfWs6LxFTdWbNxUF1N3+kDJocxgju4ZWKehTG6xrlOyeIP1zIL9vysYaTnhBd/MfauDuZ3Nlrl9J7wCNieY/dLnQqV+cOQ7vHavXdXvGPbkemO0XxfXRZ26TW2AC6Qy3nSBa/VXOcyfFzKPp3abrmp/A/j55V/Awu9gv88eeIFhdtdCB64XUTe5LSlH0eWoIgVj1Q06Af++zFxc5VxGg+Ygayqmew7Od33ml04nSg5wIXkISpULSvUXedEJaA4AssED+eu5uvWpoPTPwcHnSvHyN1C4xPlMc+HL3KO2Csmvak17SawquBbQW23mcbJPXcon5eqOfP9Mw48SfgemAIAyZ0HJmbSLryLudv9sofjdQo1ZuU=
