after_success:
  - "sbt coveralls"
  - ./project/publish
language: scala
matrix:
  include:
    -
      env: "COMMAND=ci-all PUBLISH=true"
      scala: "2.12.4"
    -
      env: "COMMAND=ci-all PUBLISH=true"
      scala: "2.11.12"
scala:
  - "2.12.4"
  - "2.11.12"
script:
  - "sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COMMAND"
  - "sbt coverageReport"
